spring:
  datasource:
    url: jdbc:h2:mem:credit_application_system_db
    username: admin
    password: admin
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true
#  springdoc:
#    swagger-ui:
#      path: /swagger-ui.html